// Generated by `contrail connect`. Re-run the command to update; do not edit.
export default {
  contrail: {
    endpoint: "http://127.0.0.1:8787",
    serviceDid: null,
    scope: null,
    collections: [
      "social.popfeed.actor.profile",
      "social.popfeed.feed.comment",
      "social.popfeed.feed.like",
      "social.popfeed.feed.list",
      "social.popfeed.feed.listItem",
      "social.popfeed.feed.review",
    ],
  },
  generate: {
    files: ["src/lib/contrail/lexicons/**/*.json"],
    outdir: "src/lib/contrail/types/",
  },
};
