// Generated by `contrail connect`. Re-run the command to update; do not edit.
export default {
  contrail: {
    endpoint: "https://api.atmo.watch",
    serviceDid: "did:web:api.atmo.watch",
    serviceAudience: "did:web:api.atmo.watch#contrail",
    scope: "rpc?aud=did:web:api.atmo.watch%23contrail&lxm=watch.atmo.notifyOfUpdate",
    protectedMethods: [
      "watch.atmo.notifyOfUpdate",
    ],
    collections: [
      "app.bsky.actor.profile",
      "social.popfeed.actor.profile",
      "social.popfeed.feed.comment",
      "social.popfeed.feed.like",
      "social.popfeed.feed.list",
      "social.popfeed.feed.listItem",
      "social.popfeed.feed.review",
    ],
  },
  generate: {
    files: ["src/lib/contrail/lexicons/source/**/*.json"],
    outdir: "src/lib/contrail/types/",
  },
};
