// Generated by `contrail connect`. Re-run the command to update; do not edit.
import { createPublicServiceClient } from "@atmo-dev/contrail/client";
import type {} from "./types/index.js";

export const contrail = createPublicServiceClient({
  endpoint: "https://api.atmo.watch",
  contractDigest: "sha256:331d01ac6beadd756e777004daf2a4e278bb3c864e91450bf7f974c4547dedd9",
  serviceDid: "did:web:api.atmo.watch#contrail",
  scope: "rpc?lxm=*&aud=did:web:api.atmo.watch%23contrail",
  serviceMethods: [
    "watch.atmo.comment.getRecord",
    "watch.atmo.comment.listRecords",
    "watch.atmo.getCursor",
    "watch.atmo.getProfile",
    "watch.atmo.like.getRecord",
    "watch.atmo.like.listRecords",
    "watch.atmo.list.getRecord",
    "watch.atmo.list.listRecords",
    "watch.atmo.listItem.getRecord",
    "watch.atmo.listItem.listRecords",
    "watch.atmo.notifyOfUpdate",
    "watch.atmo.review.getRecord",
    "watch.atmo.review.listRecords",
  ],
  collections: [
    "app.bsky.actor.profile",
    "social.popfeed.actor.profile",
    "social.popfeed.feed.comment",
    "social.popfeed.feed.like",
    "social.popfeed.feed.list",
    "social.popfeed.feed.listItem",
    "social.popfeed.feed.review",
  ],
  notifyMethod: "watch.atmo.notifyOfUpdate",
});
