// Generated by `contrail connect`. Re-run the command to update; do not edit.
import { createPublicServiceClient } from "@atmo-dev/contrail/client";
import type {} from "./types/index.js";

export const contrail = createPublicServiceClient({
  endpoint: "http://127.0.0.1:8787",
  allowInsecureHttp: true,
  contractDigest: "sha256:401ce47ba01fb8c1ba1c34821782214c2c95eb1752784630f064c659dd6b1b0f",
  serviceMethods: [
    "watch.atmo.comment.getRecord",
    "watch.atmo.comment.listRecords",
    "watch.atmo.getCursor",
    "watch.atmo.getProfile",
    "watch.atmo.like.getRecord",
    "watch.atmo.like.listRecords",
    "watch.atmo.list.getRecord",
    "watch.atmo.list.listRecords",
    "watch.atmo.listItem.getRecord",
    "watch.atmo.listItem.listRecords",
    "watch.atmo.review.getRecord",
    "watch.atmo.review.listRecords",
  ],
  collections: [
    "app.bsky.actor.profile",
    "social.popfeed.feed.comment",
    "social.popfeed.feed.like",
    "social.popfeed.feed.list",
    "social.popfeed.feed.listItem",
    "social.popfeed.feed.review",
  ],
  notifyMethod: "watch.atmo.notifyOfUpdate",
});
